### ISSUE TITLE
Introduction GUI

### ISSUE THREAD

**Issue by vbaretsky** [wallaceicy06/Betrayal#14]
Make a nice GUI interface for creating and/or joining a game.

**Comment by vbaretsky** [comment]
Also, add a tutorial at the beginning explaining controls, item effects, etc.

**Comment by wallaceicy06** [comment]
Join interface: e5f505eda54f5d0c54e67675c4def8acada304ea

**Comment by wallaceicy06** [comment]
Instructions: 860748695ea76c466bd69097b3d120a1ba1c594c
