### ISSUE TITLE
Make Traitor More Powerful in Shapeshifter Haunt

### ISSUE THREAD

**Issue by vbaretsky** [wallaceicy06/Betrayal#26]
The traitor has little chance of winning the Shapeshifter haunt. He needs to be made more powerful somehow. Allowing him to look like other players may be helpful, or giving him ridiculous boosts like automatic 1-hit kills (without a stat boost that would be visible to other players)

**Comment by lestaal** [comment]
Doubled number of keys, traitor can look like heroes, traitor guaranteed at least 1 damage per successful attack
