### ISSUE TITLE
Rearrange how to play instructions

### ISSUE THREAD

**Issue by vbaretsky** [wallaceicy06/Betrayal#46]
Make a "Controls" section which includes the instructions for attacking.

Maybe add more detail about how the haunt works - how the heroes escape the house, how many keys there are, that the traitor will have a special power.

**Comment by wallaceicy06** [comment]
50531a32ed6923870a58743c36b77320eb6da99c

**Comment by wallaceicy06** [comment]
50531a32ed6923870a58743c36b77320eb6da99c
