### ISSUE TITLE
Simplify health items

### ISSUE THREAD

**Issue by vbaretsky** [wallaceicy06/Betrayal#51]
The hearts for max health and health packs for cur health seem to confuse people (especially since the health packs do nothing if you are at max). Simplify this to a single item that increases your cur health unless you are at max, in which case it increases your max health.

Poison health items would probably just decrease cur health.

**Comment by wallaceicy06** [comment]
This should be relatively simple. Just reduce to 1 item, then change logic to increase max health if your current health is maxed out. I think it might be interesting if posion items decreased your cur health and max health, but this probably won't make a difference in practice.

**Comment by vbaretsky** [comment]
349261a50d1ae2a5682ffd7839bddb7c2458ac97 There is no longer a concept of max health - health works just like speed and weapon strength now.
