### ISSUE TITLE
Disable Combat for Phase 1

### ISSUE THREAD

**Issue by vbaretsky** [wallaceicy06/Betrayal#6]
Players can currently attack anytime. Combat should be disabled until the start of the haunt.

Possibly also don't allow heroes to attack or at least prevent friendly fire.

**Comment by vbaretsky** [comment]
66a39ccdc8492d51edb06301f76a26b03d99e134

Didn't do anything about friendly fire (anyone can attack anyone else)

**Comment by wallaceicy06** [comment]
Lol "friendly fire"
